### ISSUE TITLE
AttributeError: 'list' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#840] opened 2018-11-14 20:05 UTC
### Context

Found during testing

### Problem or idea

```
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev 2018-11-14 19:37:52,216 local data_refinery_foreman.surveyor.external_source ERROR [survey_job: 298]: Exception caught while discovering samples. Terminating survey job.
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev Traceback (most recent call last):
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 484, in create_samples_from_api
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev     sample_object = Sample.objects.get(accession_code=sample_accession_code)
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in get
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev     self.model._meta.object_name
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev data_refinery_common.models.models.Sample.DoesNotExist: Sample matching query does not exist.
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev During handling of the above exception, another exception occurred:
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev Traceback (most recent call last):
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev   File "/home/user/data_refinery_foreman/surveyor/external_source.py", line 167, in survey
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev     experiment, samples = self.discover_experiment_and_samples()
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 595, in discover_experiment_and_samples
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev     samples = self.create_samples_from_api(experiment, platform_dict)
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 519, in create_samples_from_api
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev     protocol_url=experiment.source_url + '/protocols'
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 309, in update_sample_protocol_info
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev     not new_protocol.get('text', '').strip()):
data-refinery-log-group-miserlou-dev log-stream-surveyor-docker-miserlou-dev AttributeError: 'list' object has no attribute 'strip'
```

I think this was introduced in [this PR](https://github.com/AlexsLemonade/refinebio/commit/a5c1ff53b3248d9aa2662a4dd0a05fbbd210a0c4) from September.

**Comment by Miserlou** [comment] 2018-11-14 20:06
There are a lotttt of them, so needs fixing soon.

**Comment by kurtwheeler** [comment] 2018-11-14 20:06
This is a dupe of https://github.com/AlexsLemonade/refinebio/issues/761

**Comment by kurtwheeler** [comment] 2018-11-14 20:06
I should have started on that instead of some of the other stuff I've been looking at :frowning:

**Closed** 2018-11-15 16:17 UTC
Labels: bug
