### ISSUE TITLE
Why are we failing now?

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#2342] opened 2020-06-22 16:00 UTC
### Context

We should figure out the most common reason for samples failing this weekend.

### Problem or idea

We were avoiding disk. Now that we are using attached SSDs, we might be able to recover some (many?) of these.

### Solution or next step

Let's see what the current failure reason is and figure out if we can work around it.

**Comment by wvauclain** [comment] 2020-06-22 19:48
Okay, here is what I have found so far:

By far the most common reason why samples were failing this weekend was the failure reason `"We can not process the data because it is not on the disk"`. This is a problem with the downloader jobs: somehow when processor jobs are getting queued up, they don't have their original files downloaded.

The vast majority of downloader jobs are succeeding (~55k), but only ~500 `OriginalFile`s have been updated in the last 4 days (`OriginalFile`s are updated when they are downloaded successfully), so there is something up with the downloader jobs.

Our downloader job logs are flooded with errors of the form
```
requests.exceptions.InvalidSchema: No connection adapters were found for 'anonftp@ftp-private.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/ERR/ERR227/ERR2278319/ERR2278319.sra'
```
which can ultimately be traced back to
```
File "/home/user/data_refinery_workers/downloaders/sra.py", line 106, in _download_file_http
```

So it looks like downloader jobs are trying to download SRA files from FTP URLs using HTTP, and failing as a result. Looking at the lines leading up to 106, we have this:
```
        # Try to convert old-style endpoints into new-style endpoints if possible
        try:
            if "anonftp" in download_url or "dbtest" in download_url:
                accession = download_url.split("/")[-1].split(".sra")[0]
                new_url = get_https_sra_download(accession)
                if new_url:
                    download_url = new_url
        except Exception:
            pass
        return _download_file_http(download_url, downloader_job, target_file_path)
```
Digging into `get_https_sra_download`, it makes essentially the following call:
```
curl --data "acc=ERR961847&accept-proto=http&version=2.0" https://www.ncbi.nlm.nih.gov/Traces/names/names.cgi
```
and the result of this API call is
```
#2.0
|||||||406|http protocol is not supported anymore. Please upgrade your sra toolkit installlation.
```
so `get_https_sra_download` probably threw an exception that we ignored, then we continued trying to download from the FTP URL over HTTP.

So it looks like the root cause of our processor jobs failing is that our downloaders are failing to download files from SRA because it is trying to download them over HTTP, but SRA no longer supports HTTP downloads.

There are still some questions that I need to investigate though:

1. Why aren't these downloader jobs failing? If the request throws an exception, I would expect the job to fail. But instead of failing, the job succeeded and spawned a processor job. Why?
2. Why didn't our tests catch this? Is our VCR out of date? Or do we not test this thoroughly enough?
3. Why can't I reproduce this locally? Locally I get this when running the downloader:
```
2020-06-22 18:54:51,966 local [volume: 0] data_refinery_workers.downloaders.utils DEBUG [downloader_job: 2]: Starting Downloader Job.
2020-06-22 18:54:53,553 local [volume: 0] data_refinery_workers.downloaders.sra DEBUG [downloader_job: 2]: Downloading file from https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-2/ERR961847/ERR961847.1 to /home/user/data_store/ERP004375/ERR961847/ERR961847.sra using HTTP.
2020-06-22 18:57:06,441 local [volume: 0] data_refinery_common.job_management DEBUG [processor_job: 4] [downloader_job: 2]: Queuing processor job.
2020-06-22 18:57:06,448 local [volume: 0] data_refinery_common.message_queue DEBUG: Queuing SALMON nomad job to run job SALMON with id 4.
2020-06-22 18:57:06,467 local [volume: 0] data_refinery_workers.downloaders.utils DEBUG [downloader_job: 2]: Downloader Job completed successfully.
```
4. What is the right fix for this? Should we just always download over FTP when given an FTP URL?
5. How can we stop this from happening in the future? If our tests are passing because the VCR is out of date, should we periodically refresh the VCRs? Is there a way to automate that, maybe using GitHub Actions?

**Comment by cgreene** [comment] 2020-06-22 19:50
Is it possible SRA blocked AWS IPs from using HTTPS? What if you spin up a small instance on AWS and make the same request?

**Comment by kurtwheeler** [comment] 2020-06-22 19:53
What's VCR stand for in this context?

> Should we just always download over FTP when given an FTP URL?

I would think so? I assume that if we're not it's a bug.

**Comment by wvauclain** [comment] 2020-06-22 19:55
> What's VCR stand for in this context?
The `.vcr` files from vcrpy. We could be storing an old response from NCBI before they stopped supporting HTTP downloads

**Comment by kurtwheeler** [comment] 2020-06-22 20:16
Oh right, I forgot about that thing I did :facepalm:

**Comment by wvauclain** [comment] 2020-06-23 16:05
Okay, I looked into the issue a little bit more, and it's more complex than I initially thought.

The reason why the curl command above is failing is because NCBI stopped supporting HTTP, but they still support _HTTPS_ which is what we are actually using. It looks like this is actually the reason why we are not properly converting the FTP URL into an HTTPS one:

```
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod Bad CGI request!: https://www.ncbi.nlm.nih.gov/Traces/names/names.cgi, acc=ERR204942&accept-proto=https&version=2.0
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 157, in _new_conn
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod     (self._dns_host, self.port), self.timeout, **extra_kw
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 84, in create_connection
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod     raise err
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 74, in create_connection
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod     sock.connect(sa)
data-refinery-log-group-circleci-prod log-stream-downloader-docker-circleci-prod TimeoutError: [Errno 110] Connection timed out
```

But the problem is, after downloading the full logs from AWS, this issue only happens ~500 times, and from checking the jobs themselves it looks like this always caused the jobs to fail, which is what should happen when a server goes down intermittently.

So that is why the failed jobs failed, but unfortunately that means we still do not know what happened during all of the downloader jobs that "succeeded" but did not download anything.

**Comment by wvauclain** [comment] 2020-06-24 19:14
Update: we spun up the staging server with an x1e.4xlarge instance to hopefully observe what is going on, but so far we are not seeing this behavior. I think prod was initially behaving normally too, so we will see what happens.

**Comment by kurtwheeler** [comment] 2020-06-24 19:28
:candle:

**Comment by cgreene** [comment] 2020-07-02 18:10
Should we close this one since we have a new failure reason for next sprint?

**Closed** 2020-07-06 14:53 UTC
