### ISSUE TITLE
Titles that are messed up: `is currently private and is scheduled to be released on`

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio#1395] opened 2019-07-17 15:31 UTC
### Context

A user emailed @dvenprasad about a dataset, [SRP065216](https://www.refine.bio/experiments/SRP065216/geo-accession-gse74246-is-currently-private-and-is-scheduled-to-be-released-on-mar-01-2016) having a messed up title. 
Turns out there are a [number of datasets](https://www.refine.bio/search?q=is%20currently%20private%20and%20is%20scheduled%20to%20be%20released) that have the `currently set to private` status set as their title. 

### Problem or idea

I started investigating these datasets since this shouldn't be their title but is instead a status message used for when authors upload their data but wish to keep it private until it is published in a journal somewhere. 

It appears some of these (or potentially all of these) are not our fault, but is how SRA has them titled so I think we've inherited from them. 

For example, [SRP065216 is marked incorrectly by SRA](https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP065216) but not by [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE74246). Note that I was still able to successfully download this dataset and besides the title being wrong, everything else looks fine. 

However, [SRP069086 has the correct title on SRA](https://www.refine.bio/experiments/SRP069086/geo-accession-gse77408-is-currently-private-and-is-scheduled-to-be-released-on-jan-02-2019) but the [incorrect title on refine.bio](https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP069086). Again, data still downloads fine. 

It's possible (perhaps likely) that SRA corrected their original mistake but we haven't gotten updated information from them since then? This study was published Jan 2nd of this year, so it may be that it got updated then. Currently the API shows that this entry was [last modified in Dec 2018](https://api.refine.bio/experiments/SRP069086/)
 
### Solution or next step

I think all that will be required to fix most of these problems is to refresh the information we get about the experiments from SRA. 

However, I don't know what to do about experiments that SRA still has wrong like [SRP065216](https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP065216). Can we report these to SRA to let them know? And if we did that, would they get fixed?

**Comment by cansav09** [comment] 2019-07-17 15:37
Also, looks like this affects about ~7 experiments?

**Comment by wvauclain** [comment] 2019-07-17 15:51
It looks like we should add another management command similar to https://github.com/AlexsLemonade/refinebio/pull/1355 for refreshing experiment metadata.

**Comment by wvauclain** [comment] 2019-07-24 19:31
I filed a PR for a new management command to fix this for samples that SRA has fixed, but I'm not sure what we should do about the files that SRA still has wrong so I didn't attach this issue to the PR.

**Comment by kurtwheeler** [comment] 2019-08-07 14:49
So it looks like this affects ~5 experiments now? We could report these to SRA but honestly 5 experiments is a relatively tiny amount to worry about. My vote would be that we should just close this issue for now.

I could set up a cron job to rerun this command every month but it might just be an extra load on our database and we wouldn't even be guaranteed to be updating experiments with it.

**Comment by kurtwheeler** [comment] 2019-08-07 14:52
Also, @dvenprasad we could inform the user that reported this issue originally that the issue is with SRA's metadata and that they can report this issue with SRA. If SRA fixes the issues, we can rerun that command to refresh the metadata we've pulled from them.

**Comment by cgreene** [comment] 2019-08-07 15:26
If it's five experiments and we have the accessions, let's just send a quick help ticket to SRA.

**Closed** 2019-08-19 14:05 UTC
Labels: user feedback
