### ISSUE TITLE
We need to utilize our `is_processed` fields

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#295] opened 2018-05-31 14:53 UTC
### Context

We currently have `is_processed` fields on the samples and original_files tables. However we don't ever actually set these fields to True.

### Problem or idea

Because we aren't setting these fields ever we also aren't filtering our API's responses on that field. This means that the front end is showing results including all of the data we've surveyed, not just the data we've processed. There will be data that we surveyed and decided not to process along with data that we do want to process but haven't done so yet. Those kinds of data should not be exposed to users via the front end (although our API should support querying for them).

### Solution or next step

Modify all of the processors to set `is_processed` to True for every sample they process. Make sure the API Sample endpoints support filtering on this field. Additionally, and this could be tricky, we need to find a way to enable filtering the Experiment endpoints to only return Experiments which have had all of their Samples processed.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment] 2018-05-31 14:57
We've planned to have situations where multiple processors get applied sequentially to samples (either all samples, or a subset). This is particularly pronounced at the stage where we're using ML models to fill in metadata. Could we instead whitelist certain processors and say data is "good" enough to include once one of those processors has been successfully applied to a sample? This might be as easy as having only a subset of processors that are able to set `is_processed`.

**Comment by kurtwheeler** [comment] 2018-05-31 15:04
> This might be as easy as having only a subset of processors that are able to set `is_processed`.

I think this is a good approach, basically treating the `is_processed` field like a `ready_to_serve` field

**Comment by Miserlou** [comment] 2018-05-31 15:06
[Django "Managers"](https://docs.djangoproject.com/en/2.0/topics/db/managers/#custom-managers-and-model-inheritance) are an easy way to implement this.

There is also already an `is_public` field which was designed to give us granular control on data we want to expose or not. `is_processed` was intended to be stateful information about the processor pipeline.

**Comment by cgreene** [comment] 2018-05-31 15:08
For the data we are not including but instead handling via link outs, would that be anything that doesn't have `is_processed`?

**Comment by kurtwheeler** [comment] 2018-05-31 15:15
Oh that `is_public` field looks perfect then!

**Comment by Miserlou** [comment] 2018-05-31 15:16
I think that's still undefined behavior as we didn't consider "link outs" when we did the schema. 

Doodling:

`is_public: False, is_processed: False`: Never show this result
`is_public: True, is_processed: True`: Return our results
`is_public: True, is_processed: False`: Link to `source_archive_url`

?

**Comment by kurtwheeler** [comment] 2018-05-31 15:20
Yeah I had forgotten we were gonna do that when I wrote this. That seems like a good way to do it to me.

**Comment by jaclyn-taroni** [comment] 2018-06-13 14:02
@kurtwheeler and @Miserlou - does this need to be addressed in some way for Keytar Kurt?

**Comment by Miserlou** [comment] 2018-06-13 14:03
I think that this might actually fall into the front-end domain..

**Comment by jaclyn-taroni** [comment] 2018-06-13 14:04
@ramenhog can you take a look?

**Comment by ramenhog** [comment] 2018-06-13 14:09
So basically, does the frontend have to use `is_public` and `is_processed` for showing/formatting the search results? It's not currently doing that now, no.

**Comment by kurtwheeler** [comment] 2018-06-13 14:31
Yes, I think we should probably have the frontend filter on those fields, because we'll end up with a lot of experiments/samples that we decide not to process for various reasons and don't want to offer data we didn't actually process. 

However, I do believe there is some backend work to be done to support this as we aren't setting the `is_processed` field on any table other than `datasets`.

**Comment by ramenhog** [comment] 2018-06-13 14:52
So I can definitely add in the filtering out of `is_public: false` and `is_processed: false` results. But I'm not sure we have a sample mockup of a "link to `source_archive_url` result.

Is this all still Keytar Kurt?

**Comment by kurtwheeler** [comment] 2018-06-13 14:56
I would say that "link to source_archive_url result" probably doesn't need to be in Keytar Kurt, although it'd be good to get @jaclyn-taroni or @cgreene's opinion of it.

I do think that we should do the filtering for KK, because otherwise we'll have so many samples that can't actually be downloaded. I guess until we actually do link out to `source_archive_url`, just also filter out `is_public`: True, `is_processed`: False cases from appearing in the frontend as well.

**Comment by jaclyn-taroni** [comment] 2018-06-13 15:20
> I would say that "link to source_archive_url result" probably doesn't need to be in Keytar Kurt

Agreed since this refers to samples on platforms that are not supported and we are concerned only with samples on the supported Affymetrix, Illumina BeadArray, and sequencing instruments for Keytar Kurt

**Comment by ramenhog** [comment] 2018-06-14 14:15
Just to clarify, are we filtering samples in the samples table or experiments on the search results page?

**Comment by cgreene** [comment] 2018-06-15 12:38
Was there a conversation offline or is this still an open question?

**Comment by ramenhog** [comment] 2018-06-15 13:16
It's still an open question

**Comment by cgreene** [comment] 2018-06-15 13:36
I think we should use @Miserlou's schema above at this point. Filter the API query for `is_public` to avoid having to deal with those since we will not show them. For now you can also filter what is shown to require `is_processed`. We'll have to design a link-out approach for the `is_processed = false` state but that's post-Keytar.

**Comment by jaclyn-taroni** [comment] 2018-06-17 15:49
Was this closed by #318 ?

**Comment by cgreene** [comment] 2018-06-20 14:44
@Miserlou - see @jaclyn-taroni's question - closed by #318?

**Comment by Miserlou** [comment] 2018-06-20 14:58
Yep, I think so.

**Closed by Miserlou** 2018-06-20 14:58 UTC
Labels: api, processor, review
