### ISSUE TITLE
Non matching Quant Files

### ISSUE THREAD

**Issue by boooooogey** [AlexsLemonade/refinebio#1996] opened 2019-12-12 23:34 UTC
### Context

Merging all samples in the dataset into a big matrix is problematic. In the dataset, the quant files are not uniform.

### Problem

Different files have different numbers and types of transcripts.  For example, ENST00000643979 is in  DRP001150/DRR013807_quant.sf but not in DRP001150/DRR013806_quant.sf for the human dataset.

**Comment by kurtwheeler** [comment] 2019-12-16 15:30
This could be related to the files being generated with different versions of salmon or because they used different versions of transcriptome indices. Seems more likely to be the former.

Seems like the way to start looking into this is to dig into the history here and figure out if different versions of salmon were in fact used.

**Comment by jaclyn-taroni** [comment] 2019-12-16 15:32
@kurtwheeler we had to generate new transcriptome indices because the older indices we not compatible with the newer version of Salmon, so it is likely _both_.

**Comment by cgreene** [comment] 2019-12-16 15:43
I think there are a couple things going on here.

First, we'll want to make sure the docs note in the quant compendia section that we have used different versions of salmon & transcriptome builds. This caveat is important to users. One could still tximport or otherwise combine within versions and then do a merge afterwards. I think this is the best outcome for this ticket.

However, one thing that's confusing is that both of these samples come from `DRP001150`. That's odd, because I think I recall that @arielsvn wrote code to go back and re-run all samples that had existing quant files from old salmon/indices if the full experiment hadn't been processed already via tximport. That means that we should always have quant files for the same versions within an experiment.

@arielsvn : can you refresh my memory on what happened with this process?

**Comment by arielsvn** [comment] 2019-12-16 15:49
Yes, we re-processed a lot of those samples, but there might be some that failed so they might not have updated `quant.sf` files. I'm going to check those two samples to see what indices were used for their `quant.sf` files.

**Comment by arielsvn** [comment] 2019-12-16 15:58
Just confirmed, those two samples were processed with different versions of salmon:

```
>>> Sample.objects.get(accession_code='DRR013807').get_most_recent_quant_sf_file().result.organism_index
<OrganismIndex: OrganismIndex 152: HOMO_SAPIENS [TRANSCRIPTOME_LONG] - salmon 0.9.1>
>>> Sample.objects.get(accession_code='DRR013806').get_most_recent_quant_sf_file().result.organism_index
<OrganismIndex: OrganismIndex 539: HOMO_SAPIENS [TRANSCRIPTOME_LONG] - salmon 0.13.1>
```

**Comment by cgreene** [comment] 2019-12-16 17:39
@arielsvn : I imagine this means tximport failed as well. Can I interpret this to mean that `DRR013807` failed when you ran it with salmon 0.13.1. Do we know what the error was?

**Comment by arielsvn** [comment] 2019-12-16 18:45
> Can I interpret this to mean that DRR013807 failed when you ran it with salmon 0.13.1

That's what I thought, but it seems like we never re-ran salmon v0.13.1 for sample [DRR013807](https://www.refine.bio/samples/DRR013807). Latest salmon job for this sample ran on 04/03/2019 and we updated salmon later with https://github.com/AlexsLemonade/refinebio/pull/1293

We could try re-processing it to see if we generate a new `quant.sf` file. I think at some point we had a check not to queue processor jobs if there was already a `quant.sf` file, we modified it to also check that the file had been generated with the latest version of salmon.

**Comment by cgreene** [comment] 2019-12-16 18:50
Exciting! This means there might be some more places where we can get tximport to succeed. I'll create a new issue for this.

@boooooogey : I now have a good enough understanding to summarize things for you. We upgraded salmon at one point. This required us to rebuild the transcriptome indices, so these files were processed with different transcriptome indices. I suspect there are a few large batches that are consistent. You should be able to merge over those if you want to (though, to be fair, if you want merged data you may be better served with our normalized/imputed compendia: https://www.refine.bio/compendia#normalized

**Comment by arielsvn** [comment] 2020-04-13 21:11
This experiment [DRP001150](https://www.refine.bio/experiments/DRP001150/a-promoter-level-mammalian-expression-atlas-human-rna-seq)  is now fully processed. I'm gonna follow up in #2006 to re-process all similar experiments. Thanks for filing this!

**Closed by arielsvn** 2020-04-13 21:11 UTC
